name: Upload Files to CF Domain and Update Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Delete old data
      run: |
        rm -rf ./ip-info
        rm -rf ./ips

    - name: Get source data
      run: |
        wget -N https://zip.cm.edu.kg -O ip.zip
        unzip ip.zip -d ./ips
        rm ip.zip

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests pandas tqdm

    - name: Run IP info collector
      run: python ip_info_collector.py

    - name: Set script permissions
      run: chmod +x ips_to_cfkv.sh

    - name: Upload files using SH script
      env:
        CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
        CF_TOKEN: ${{ secrets.CF_TOKEN }}
        FOLDER_PATH: "ip-info/443,ip-info/mrked"  # 多个目录用逗号分隔
      run: ./ips_to_cfkv.sh

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -am "自动更新IP信息文件"
        git push
